language: python
python:
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yang.chen
  password:
    secure: qr4U589u6YrAI9L9CT8C3AsivU1oawqpaIG76nszw9klNdNJ479dKQ38+K8j2Dt1e9B01W0PRNGLrjAcbKFsL5qVU00shx6CmgZXr2TLyH+88K5T7cDPIN3P+NDzu0ZLAYMGYSimCrlnBGIJuMriikLh7RS+ldkQSEBfI6OAQje37/Hf3l5sIVAxgNMM3DhoKP4+gnNcl5MIGOqJB7TQPHH7RJEin8S+KiWjgTygdq9wHXkwEKxjq8jddPqkmKxBRs9iKR/PV6A6DvmaaqRa5t2CCopLz7QiSn/pUbyKTf7c+a37VDuiYrZ8BwNREuX85C2zyayrbYbsenB4gMaC4GKeYl+Z0yIFEx2uUY6z1liFctJr8tlu98tZrKkYBomaUtrh2UEEVK9GGgPyBtdvPMoOshEOzLSVE4isuxZhYdE0skkPDhscpRT2tMZqjiqA9dUhFkFDZyGXD7NORKUUWwTfZeM5y4RmxzkLxK2fga3mwbqPwftPnsfwzGrAkEXprofNNpYhLg0NXalpZyWMHKwykwWBI9lhnYrJbLO8ce4LPaNbUyMixf+eYBmCXR/9iuVk0ADVBY4On0X36MjTx8KglQkcWaMIkbpwBITUW4D1FU1v6u9JgW8p/S9Z2LO2p0Ex5hcqjYcOkd3KV/OWFS0Y07iZ4kQ2cRY7PH1eD6E=
  on:
    branch: master
    repo: nehcgnay/fcsy
